import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(__dirname, "../../.env.local") });

const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.error("Error: MONGODB_URI is not defined in .env.local");
  process.exit(1);
}

interface SeedFurniture {
  productName: string;
  category: string;
  brand: string;
  price: number;
  image: string;
  storeName: string;
  productUrl: string;
  style: string;
  rating: number;
  description: string;
  inStock: boolean;
  tags: string[];
}

const furnitureItems: SeedFurniture[] = [
  // SOFAS (5)
  {
    productName: "Harmony L-Shape Sectional Sofa",
    category: "Sofa",
    brand: "IKEA",
    price: 74999,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/harmony-sectional-sofa",
    style: "Modern",
    rating: 4.5,
    description: "Spacious L-shaped sectional sofa with deep seating and premium fabric upholstery. Perfect for large living rooms.",
    inStock: true,
    tags: ["sectional", "fabric", "large", "family"],
  },
  {
    productName: "Velvet Chesterfield 3-Seater",
    category: "Sofa",
    brand: "Pepperfry",
    price: 52999,
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/velvetchesterfield3seater.html",
    style: "Luxury",
    rating: 4.3,
    description: "Classic Chesterfield sofa in rich velvet upholstery with rolled arms and deep button tufting.",
    inStock: true,
    tags: ["velvet", "chesterfield", "classic", "3-seater"],
  },
  {
    productName: "Nordic Fabric 2-Seater Sofa",
    category: "Sofa",
    brand: "IKEA",
    price: 29999,
    image: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/nordic-fabric-sofa",
    style: "Scandinavian",
    rating: 4.4,
    description: "Minimalist 2-seater sofa with light wood legs and washable fabric cover in neutral tones.",
    inStock: true,
    tags: ["minimalist", "washable", "light", "compact"],
  },
  {
    productName: "Urban Leather Recliner Sofa",
    category: "Sofa",
    brand: "Urban Ladder",
    price: 89999,
    image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600",
    storeName: "Urban Ladder",
    productUrl: "https://www.urbanladder.com/urban-leather-recliner",
    style: "Modern",
    rating: 4.6,
    description: "Premium Italian leather recliner with motorized controls and USB charging ports.",
    inStock: true,
    tags: ["leather", "recliner", "motorized", "premium"],
  },
  {
    productName: "Bohemian Cotton Daybed Sofa",
    category: "Sofa",
    brand: "HomeTown",
    price: 34999,
    image: "https://images.unsplash.com/photo-1550254478-ead40cc54513?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/bohemian-cotton-daybed",
    style: "Bohemian",
    rating: 4.1,
    description: "Versatile daybed with boho-print cotton upholstery, perfect for studio apartments.",
    inStock: true,
    tags: ["daybed", "cotton", "boho", "versatile"],
  },

  // CHAIRS (5)
  {
    productName: "Ergonomic Mesh Office Chair",
    category: "Chair",
    brand: "Godrej Interio",
    price: 15999,
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600",
    storeName: "Godrej Interio",
    productUrl: "https://www.godrejinterio.com/ergonomic-mesh-chair",
    style: "Modern",
    rating: 4.4,
    description: "Fully adjustable ergonomic office chair with lumbar support, headrest, and breathable mesh back.",
    inStock: true,
    tags: ["ergonomic", "office", "mesh", "adjustable"],
  },
  {
    productName: "Mid-Century Accent Armchair",
    category: "Chair",
    brand: "Pepperfry",
    price: 18999,
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/midcentury-accent-armchair.html",
    style: "Mid-Century",
    rating: 4.5,
    description: "Iconic mid-century armchair with solid wood legs and premium linen upholstery.",
    inStock: true,
    tags: ["mid-century", "accent", "linen", "wooden"],
  },
  {
    productName: "Scandinavian Lounge Chair",
    category: "Chair",
    brand: "IKEA",
    price: 24999,
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/scandinavian-lounge-chair",
    style: "Scandinavian",
    rating: 4.7,
    description: "Elegant lounge chair with curved birch veneer frame and soft wool-blend cushion.",
    inStock: true,
    tags: ["lounge", "birch", "wool", "curved"],
  },
  {
    productName: "Industrial Metal Dining Chair",
    category: "Chair",
    brand: "Nilkamal",
    price: 4999,
    image: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600",
    storeName: "Flipkart",
    productUrl: "https://www.flipkart.com/industrial-metal-dining-chair",
    style: "Industrial",
    rating: 4.2,
    description: "Set of 2 rustic industrial dining chairs with powder-coated metal frame and wooden seat.",
    inStock: true,
    tags: ["industrial", "metal", "dining", "rustic"],
  },
  {
    productName: "Woven Rattan Peacock Chair",
    category: "Chair",
    brand: "HomeTown",
    price: 12999,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/woven-rattan-peacock-chair",
    style: "Bohemian",
    rating: 4.3,
    description: "Handwoven natural rattan peacock chair, a statement piece for any living space.",
    inStock: true,
    tags: ["rattan", "peacock", "handwoven", "statement"],
  },

  // TABLES (5)
  {
    productName: "Oakwood Extendable Dining Table",
    category: "Table",
    brand: "Urban Ladder",
    price: 42999,
    image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600",
    storeName: "Urban Ladder",
    productUrl: "https://www.urbanladder.com/oakwood-extendable-dining-table",
    style: "Modern",
    rating: 4.5,
    description: "Solid oak dining table that extends from 6-seater to 8-seater with easy-slide mechanism.",
    inStock: true,
    tags: ["oak", "extendable", "dining", "6-8-seater"],
  },
  {
    productName: "Marble Top Coffee Table",
    category: "Table",
    brand: "Pepperfry",
    price: 18999,
    image: "https://images.unsplash.com/photo-1532372576444-dda954194ad0?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/marble-top-coffee-table.html",
    style: "Luxury",
    rating: 4.6,
    description: "Italian marble top coffee table with brushed gold legs. A luxurious centerpiece for your living room.",
    inStock: true,
    tags: ["marble", "coffee", "gold", "luxury"],
  },
  {
    productName: "Industrial Pipe Console Table",
    category: "Table",
    brand: "IKEA",
    price: 12999,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/industrial-pipe-console-table",
    style: "Industrial",
    rating: 4.3,
    description: "Rustic console table with reclaimed wood top and black iron pipe frame.",
    inStock: true,
    tags: ["console", "pipe", "rustic", "reclaimed"],
  },
  {
    productName: "Nesting Side Tables (Set of 3)",
    category: "Table",
    brand: "Nilkamal",
    price: 7499,
    image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600",
    storeName: "Amazon India",
    productUrl: "https://www.amazon.in/nesting-side-tables-set",
    style: "Minimalist",
    rating: 4.1,
    description: "Set of 3 nesting side tables in different sizes. Space-saving and versatile.",
    inStock: true,
    tags: ["nesting", "side-table", "space-saving", "set"],
  },
  {
    productName: "Live Edge Walnut Dining Table",
    category: "Table",
    brand: "Urban Ladder",
    price: 68999,
    image: "https://images.unsplash.com/photo-1604074131665-7a4b13870ab5?w=600",
    storeName: "Urban Ladder",
    productUrl: "https://www.urbanladder.com/live-edge-walnut-dining-table",
    style: "Modern",
    rating: 4.8,
    description: "Handcrafted live edge walnut dining table with natural wood grain and steel legs.",
    inStock: true,
    tags: ["live-edge", "walnut", "handcrafted", "dining"],
  },

  // BEDS (4)
  {
    productName: "King Size Platform Bed with Storage",
    category: "Bed",
    brand: "Sleepwell",
    price: 45999,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600",
    storeName: "Sleepwell",
    productUrl: "https://www.sleepwell.in/king-size-platform-bed",
    style: "Modern",
    rating: 4.5,
    description: "King size platform bed with hydraulic storage and padded headboard. Premium engineered wood construction.",
    inStock: true,
    tags: ["king", "platform", "storage", "hydraulic"],
  },
  {
    productName: "Solid Sheesham Wood Cot",
    category: "Bed",
    brand: "Godrej Interio",
    price: 38999,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600",
    storeName: "Godrej Interio",
    productUrl: "https://www.godrejinterio.com/solid-sheesham-wood-cot",
    style: "Traditional",
    rating: 4.4,
    description: "Handcrafted solid Sheesham wood cot with intricate carvings. Durable and elegant.",
    inStock: true,
    tags: ["sheesham", "solid-wood", "handcrafted", "traditional"],
  },
  {
    productName: "Upholstered King Bed - Blush Pink",
    category: "Bed",
    brand: "Pepperfry",
    price: 32999,
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/upholstered-king-bed-blush.html",
    style: "Modern",
    rating: 4.3,
    description: "Velvet upholstered king bed in blush pink with diamond-tufted headboard.",
    inStock: true,
    tags: ["upholstered", "velvet", "king", "tufted"],
  },
  {
    productName: "Minimalist Oak Queen Bed Frame",
    category: "Bed",
    brand: "IKEA",
    price: 22999,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/minimalist-oak-queen-bed",
    style: "Minimalist",
    rating: 4.6,
    description: "Clean-lined queen bed frame in natural oak with slatted headboard.",
    inStock: true,
    tags: ["minimalist", "oak", "queen", "slatted"],
  },

  // LAMPS (4)
  {
    productName: "Brass Arc Floor Lamp",
    category: "Lamp",
    brand: "Pepperfry",
    price: 8999,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/brass-arc-floor-lamp.html",
    style: "Modern",
    rating: 4.5,
    description: "Elegant brass arc floor lamp with adjustable arm and dimmable LED compatible.",
    inStock: true,
    tags: ["brass", "arc", "floor", "adjustable"],
  },
  {
    productName: "Industrial Pendant Light Trio",
    category: "Lamp",
    brand: "Urban Ladder",
    price: 6499,
    image: "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600",
    storeName: "Urban Ladder",
    productUrl: "https://www.urbanladder.com/industrial-pendant-light-trio",
    style: "Industrial",
    rating: 4.4,
    description: "Set of 3 adjustable pendant lights with matte black finish and exposed bulb design.",
    inStock: true,
    tags: ["pendant", "industrial", "black", "set-of-3"],
  },
  {
    productName: "Scandinavian Table Lamp with Linen Shade",
    category: "Lamp",
    brand: "IKEA",
    price: 3499,
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/scandinavian-table-lamp",
    style: "Scandinavian",
    rating: 4.3,
    description: "Warm white table lamp with birch base and natural linen drum shade.",
    inStock: true,
    tags: ["table-lamp", "birch", "linen", "warm"],
  },
  {
    productName: "Crystal Chandelier - 8 Light",
    category: "Lamp",
    brand: "HomeTown",
    price: 14999,
    image: "https://images.unsplash.com/photo-1543198126-a8ad8e47fb22?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/crystal-chandelier-8-light",
    style: "Luxury",
    rating: 4.7,
    description: "Stunning 8-light crystal chandelier with chrome finish. Adds grandeur to any room.",
    inStock: true,
    tags: ["chandelier", "crystal", "chrome", "8-light"],
  },

  // RUGS (3)
  {
    productName: "Hand-Tufted Wool Area Rug 8x10",
    category: "Rug",
    brand: "Pepperfry",
    price: 22999,
    image: "https://images.unsplash.com/photo-1600166898405-da9535204843?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/hand-tufted-wool-rug.html",
    style: "Modern",
    rating: 4.6,
    description: "Premium hand-tufted wool area rug in contemporary geometric pattern. 8x10 feet.",
    inStock: true,
    tags: ["wool", "hand-tufted", "geometric", "8x10"],
  },
  {
    productName: "Jute Braided Round Rug 5ft",
    category: "Rug",
    brand: "HomeTown",
    price: 5999,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/jute-braided-round-rug",
    style: "Bohemian",
    rating: 4.2,
    description: "Eco-friendly hand-braided jute rug in natural tone. 5 feet diameter.",
    inStock: true,
    tags: ["jute", "braided", "round", "eco-friendly"],
  },
  {
    productName: "Persian Style Medallion Rug 6x9",
    category: "Rug",
    brand: "Nilkamal",
    price: 8999,
    image: "https://images.unsplash.com/photo-1584367290038-49bbd2a3f1d4?w=600",
    storeName: "Flipkart",
    productUrl: "https://www.flipkart.com/persian-style-medallion-rug",
    style: "Traditional",
    rating: 4.1,
    description: "Machine-made Persian style rug with ornate medallion design. Easy to clean.",
    inStock: true,
    tags: ["persian", "medallion", "machine-made", "ornate"],
  },

  // CURTAINS (3)
  {
    productName: "Blackout Velvet Curtains - Navy Blue",
    category: "Curtains",
    brand: "IKEA",
    price: 4999,
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/blackout-velvet-curtains",
    style: "Modern",
    rating: 4.5,
    description: "100% blackout velvet curtains in navy blue. Thermal insulated and noise reducing.",
    inStock: true,
    tags: ["blackout", "velvet", "thermal", "navy"],
  },
  {
    productName: "Sheer Linen Curtains - White",
    category: "Curtains",
    brand: "Pepperfry",
    price: 2999,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/sheer-linen-curtains-white.html",
    style: "Scandinavian",
    rating: 4.3,
    description: "Light and airy sheer linen curtains in white. Allows soft natural light to filter through.",
    inStock: true,
    tags: ["sheer", "linen", "white", "light"],
  },
  {
    productName: "Geometric Print Cotton Curtains",
    category: "Curtains",
    brand: "HomeTown",
    price: 1999,
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/geometric-print-cotton-curtains",
    style: "Modern",
    rating: 4.0,
    description: "Contemporary cotton curtains with bold geometric print. Machine washable.",
    inStock: true,
    tags: ["cotton", "geometric", "washable", "contemporary"],
  },

  // TV UNITS (3)
  {
    productName: "Floating Wall-Mounted TV Unit",
    category: "TV Unit",
    brand: "IKEA",
    price: 14999,
    image: "https://images.unsplash.com/photo-1615876234886-fd9a39fda97f?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/floating-wall-tv-unit",
    style: "Minimalist",
    rating: 4.4,
    description: "Sleek wall-mounted TV unit with soft-close drawers and cable management.",
    inStock: true,
    tags: ["floating", "wall-mounted", "cable-management", "minimalist"],
  },
  {
    productName: "Industrial Reclaimed Wood TV Console",
    category: "TV Unit",
    brand: "Urban Ladder",
    price: 24999,
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600",
    storeName: "Urban Ladder",
    productUrl: "https://www.urbanladder.com/industrial-reclaimed-wood-tv-console",
    style: "Industrial",
    rating: 4.5,
    description: "Rustic TV console with reclaimed wood shelves and iron frame. Fits TVs up to 65 inches.",
    inStock: true,
    tags: ["industrial", "reclaimed", "rustic", "65-inch"],
  },
  {
    productName: "High-Gloss Lacquer TV Cabinet",
    category: "TV Unit",
    brand: "Godrej Interio",
    price: 32999,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600",
    storeName: "Godrej Interio",
    productUrl: "https://www.godrejinterio.com/high-gloss-lacquer-tv-cabinet",
    style: "Modern",
    rating: 4.6,
    description: "Premium high-gloss lacquer TV cabinet with LED backlighting and ample storage.",
    inStock: true,
    tags: ["high-gloss", "lacquer", "LED", "premium"],
  },

  // SHELVES (3)
  {
    productName: "5-Tier Ladder Bookshelf",
    category: "Shelf",
    brand: "IKEA",
    price: 8999,
    image: "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/5-tier-ladder-bookshelf",
    style: "Industrial",
    rating: 4.3,
    description: "Leaning ladder-style bookshelf with 5 tiers. Black metal frame with wooden shelves.",
    inStock: true,
    tags: ["ladder", "bookshelf", "5-tier", "metal-wood"],
  },
  {
    productName: "Modular Wall Storage System",
    category: "Shelf",
    brand: "Pepperfry",
    price: 16999,
    image: "https://images.unsplash.com/photo-1558997519-8e142b9c2d29?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/modular-wall-storage.html",
    style: "Minimalist",
    rating: 4.4,
    description: "Customizable modular wall storage system. Mix and match cubes, shelves, and cabinets.",
    inStock: true,
    tags: ["modular", "wall-storage", "customizable", "cubes"],
  },
  {
    productName: "Rotating Bookcase Tower",
    category: "Shelf",
    brand: "Nilkamal",
    price: 6499,
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600",
    storeName: "Amazon India",
    productUrl: "https://www.amazon.in/rotating-bookcase-tower",
    style: "Modern",
    rating: 4.2,
    description: "360-degree rotating bookcase with 6 shelves. Compact and space-efficient design.",
    inStock: true,
    tags: ["rotating", "360-degree", "compact", "6-shelf"],
  },

  // PLANTS (3)
  {
    productName: "Artificial Fiddle Leaf Fig Tree 5ft",
    category: "Plant",
    brand: "HomeTown",
    price: 4999,
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/artificial-fiddle-leaf-fig-tree",
    style: "Modern",
    rating: 4.1,
    description: "Realistic artificial fiddle leaf fig tree in ceramic pot. No maintenance needed.",
    inStock: true,
    tags: ["artificial", "fiddle-leaf", "indoor", "low-maintenance"],
  },
  {
    productName: "Ceramic Planter Set - Terracotta",
    category: "Plant",
    brand: "Pepperfry",
    price: 2499,
    image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/ceramic-planter-set.html",
    style: "Bohemian",
    rating: 4.3,
    description: "Set of 3 handcrafted ceramic planters in terracotta finish with drainage holes.",
    inStock: true,
    tags: ["ceramic", "planter", "terracotta", "handcrafted"],
  },
  {
    productName: "Hanging Macrame Plant Holder",
    category: "Plant",
    brand: "HomeTown",
    price: 1299,
    image: "https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=600",
    storeName: "Amazon India",
    productUrl: "https://www.amazon.in/hanging-macrame-plant-holder",
    style: "Bohemian",
    rating: 4.4,
    description: "Handwoven macrame plant hanger with wooden bead accents. Fits standard 6-inch pots.",
    inStock: true,
    tags: ["macrame", "hanging", "bohemian", "handwoven"],
  },

  // MIRRORS (3)
  {
    productName: "Arch Full-Length Floor Mirror",
    category: "Mirror",
    brand: "Pepperfry",
    price: 14999,
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/arch-full-length-mirror.html",
    style: "Modern",
    rating: 4.7,
    description: "Elegant arch-shaped full-length mirror with slim black metal frame. Can lean against wall.",
    inStock: true,
    tags: ["arch", "full-length", "floor", "black-frame"],
  },
  {
    productName: "Ornate Gold Wall Mirror 30 inch",
    category: "Mirror",
    brand: "HomeTown",
    price: 7999,
    image: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/ornate-gold-wall-mirror",
    style: "Luxury",
    rating: 4.5,
    description: "Ornate baroque-style wall mirror with antique gold finish frame. 30 inches diameter.",
    inStock: true,
    tags: ["ornate", "gold", "baroque", "wall-mount"],
  },
  {
    productName: "Frameless Beveled Edge Mirror",
    category: "Mirror",
    brand: "Nilkamal",
    price: 3499,
    image: "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=600",
    storeName: "Flipkart",
    productUrl: "https://www.flipkart.com/frameless-beveled-edge-mirror",
    style: "Minimalist",
    rating: 4.2,
    description: "Frameless mirror with beveled edges. Clean and minimalist design, wall-mountable.",
    inStock: true,
    tags: ["frameless", "beveled", "minimalist", "wall-mount"],
  },

  // CLOCKS (2)
  {
    productName: "Oversized Industrial Wall Clock",
    category: "Clock",
    brand: "Pepperfry",
    price: 3999,
    image: "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/oversized-industrial-wall-clock.html",
    style: "Industrial",
    rating: 4.4,
    description: "Large 24-inch industrial wall clock with distressed metal finish and silent mechanism.",
    inStock: true,
    tags: ["oversized", "industrial", "24-inch", "silent"],
  },
  {
    productName: "Wooden Nordic Wall Clock",
    category: "Clock",
    brand: "IKEA",
    price: 1999,
    image: "https://images.unsplash.com/photo-1508962914676-134849a727f0?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/wooden-nordic-wall-clock",
    style: "Scandinavian",
    rating: 4.3,
    description: "Minimalist wall clock in natural birch with simple hour markers. Silent quartz movement.",
    inStock: true,
    tags: ["wooden", "nordic", "birch", "silent"],
  },

  // CUSHIONS (3)
  {
    productName: "Velvet Cushion Cover Set of 6",
    category: "Cushion",
    brand: "Pepperfry",
    price: 1999,
    image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600",
    storeName: "Pepperfry",
    productUrl: "https://www.pepperfry.com/velvet-cushion-cover-set.html",
    style: "Luxury",
    rating: 4.4,
    description: "Premium velvet cushion covers in jewel tones. Set of 6, 18x18 inches each.",
    inStock: true,
    tags: ["velvet", "covers", "jewel-tones", "set-of-6"],
  },
  {
    productName: "Hand-Embroidered Cushion 16x16",
    category: "Cushion",
    brand: "HomeTown",
    price: 899,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600",
    storeName: "HomeTown",
    productUrl: "https://www.hometown.in/hand-embroidered-cushion",
    style: "Bohemian",
    rating: 4.2,
    description: "Hand-embroidered cotton cushion with folk art motif. Filled with hypoallergenic fiber.",
    inStock: true,
    tags: ["embroidered", "cotton", "folk-art", "hypoallergenic"],
  },
  {
    productName: "Memory Foam Floor Cushion",
    category: "Cushion",
    brand: "Sleepwell",
    price: 1499,
    image: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600",
    storeName: "Sleepwell",
    productUrl: "https://www.sleepwell.in/memory-foam-floor-cushion",
    style: "Minimalist",
    rating: 4.5,
    description: "Thick memory foam floor cushion with washable cotton cover. Great for meditation and seating.",
    inStock: true,
    tags: ["memory-foam", "floor", "washable", "meditation"],
  },

  // CABINETS (3)
  {
    productName: "Walnut Finish Display Cabinet",
    category: "Cabinet",
    brand: "Godrej Interio",
    price: 28999,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    storeName: "Godrej Interio",
    productUrl: "https://www.godrejinterio.com/walnut-display-cabinet",
    style: "Modern",
    rating: 4.5,
    description: "Elegant display cabinet with glass doors, LED lighting, and walnut finish.",
    inStock: true,
    tags: ["display", "glass", "LED", "walnut"],
  },
  {
    productName: "Modular Kitchen Storage Cabinet",
    category: "Cabinet",
    brand: "IKEA",
    price: 18999,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600",
    storeName: "IKEA India",
    productUrl: "https://www.ikea.com/in/en/p/modular-kitchen-storage-cabinet",
    style: "Minimalist",
    rating: 4.4,
    description: "Modular storage cabinet with adjustable shelves. White matte finish.",
    inStock: true,
    tags: ["modular", "kitchen", "adjustable", "white"],
  },
  {
    productName: "Rattan Sideboard Cabinet",
    category: "Cabinet",
    brand: "Urban Ladder",
    price: 22999,
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600",
    storeName: "Urban Ladder",
    productUrl: "https://www.urbanladder.com/rattan-sideboard-cabinet",
    style: "Bohemian",
    rating: 4.6,
    description: "Beautiful rattan sideboard with cane weave doors and solid wood frame.",
    inStock: true,
    tags: ["rattan", "sideboard", "cane", "handwoven"],
  },
];

async function seedFurniture() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI!);
  console.log("Connected to MongoDB successfully.");

  const FurnitureItemSchema = new mongoose.Schema(
    {
      productName: { type: String, required: true, trim: true },
      category: { type: String, required: true, trim: true },
      brand: { type: String, default: "", trim: true },
      price: { type: Number, required: true, min: 0 },
      image: { type: String, default: "" },
      storeName: { type: String, required: true, trim: true },
      productUrl: { type: String, required: true, trim: true },
      style: { type: String, default: "", trim: true },
      rating: { type: Number, min: 0, max: 5, default: 0 },
      description: { type: String, default: "" },
      inStock: { type: Boolean, default: true },
      tags: { type: [String], default: [] },
    },
    { timestamps: true }
  );

  const FurnitureModel =
    mongoose.models.FurnitureItem ||
    mongoose.model("FurnitureItem", FurnitureItemSchema);

  console.log("Clearing existing furniture items...");
  await FurnitureModel.deleteMany({});

  console.log(`Inserting ${furnitureItems.length} furniture items...`);
  const result = await FurnitureModel.insertMany(furnitureItems);
  console.log(`Successfully inserted ${result.length} furniture items.`);

  const categories = [...new Set(furnitureItems.map((f) => f.category))];
  console.log(`\nCategories seeded: ${categories.join(", ")}`);

  const brands = [...new Set(furnitureItems.map((f) => f.brand))];
  console.log(`Brands seeded: ${brands.join(", ")}`);

  const styles = [...new Set(furnitureItems.map((f) => f.style))];
  console.log(`Styles seeded: ${styles.join(", ")}`);

  const priceRange = furnitureItems.map((f) => f.price);
  console.log(
    `Price range: ₹${Math.min(...priceRange).toLocaleString("en-IN")} - ₹${Math.max(...priceRange).toLocaleString("en-IN")}`
  );

  await mongoose.disconnect();
  console.log("\nFurniture seeding completed. Disconnected from MongoDB.");
}

seedFurniture().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
